### ISSUE TITLE
Troubleshooting: Can't get images to show

### ISSUE THREAD

**Issue by brandatpin** [cloudstitch/cloudstitch-sketch-plugin#2]
This works great for text. Could I get further instructions on adding an image, specifically an image URL. what syntax do I need to put in the cell to reference the image? thanks!!

**Comment by gopatrik** [comment]
Hi @brandatpin, I fixed this issue and made a pull request. Keep an eye on that :-)

**Comment by brandatpin** [comment]
thanks!
